services:
  audiobookshelf-exporter:
    image: ghcr.io/craftwork2720/audiobookshelf-meta-exporter:latest
    container_name: audiobookshelf-exporter
    ports:
      - "8080:8080"
    volumes:
      - "/path/to/audiobookshelf/config:/config:ro"
      - "/path/to/audiobookshelf/metadata/items:/items:ro"
      - "./data/exported:/exported:rw"
    environment:
      PORT: 8080
    restart: unless-stopped
